---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-client-deployment
  labels:
    app: chat-client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chat-client
  template:
    metadata:
      labels:
        app: chat-client
    spec:
      containers:
      - name: chat-client
        image: mycluster-registry:8050/{{ .Values.ChatClientDockerTag }}
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: chat-client
  name: chat-client-service
spec:
  ports:
  - name: 80-8000
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: chat-client
  type: ClusterIP
