---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-client-deployment
  labels:
    app: chat-client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chat-client
  template:
    metadata:
      labels:
        app: chat-client
    spec:
      containers:
      - name: chat-client
        image: mycluster-registry:8050/{{ .Values.ChatClientDockerTag }}
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: chat-client
  name: chat-client-service
spec:
  ports:
  - name: 80-8000
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: chat-client
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-broker--deployment
  labels:
    app: message-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-broker
  template:
    metadata:
      labels:
        app: message-broker
    spec:
      containers:
      - name: redis
        image: redis:7.0
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: message-broker
  name: message-broker-service
spec:
  ports:
  - name: 6379-6379
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: message-broker
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-client-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: chat-client-service
            port:
              number: 80
        path: /
        pathType: Prefix
