---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-client-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: default-strip-prefix@kubernetescrd
spec:
  rules:
  - http:
      paths:
      - path: /chat-client
        pathType: Prefix
        backend:
          service:
            name: chat-client-service
            port:
              number: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix
spec:
  #stripPrefixRegex:
  #  regex:
  #  - ^/[^/]+
  stripPrefix:
    prefixes:
      - /chat-client
